Connect API to Bookstore
Epaltechs/Bookstore pull request #4
Opened 2022-06-15 22:08 UTC by Epaltechs

### In this branch of the project, I have implemented the following:
- Add redux-thunk to the project.
- Use fetch for making API calls.
- Fetch book list from Bookstore API on Books page load.
- Add an Action Creator, that returns a function.
- Fetch list of books.
- Dispatch another action that pass API response to reducer and updates the state.
- Refactor add book and remove book features to persist changes in the server.
- Change existing Action Creators, so they return functions.
- Make changes by using API.
- Dispatch an action that updates the state accordingly.

2022-06-15 22:26 UTC, ShahierNashaat requested changes
Hi @Epaltechs , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 22:26 UTC, ShahierNashaat commented on src/redux/books/books.js
> +      return state.filter((book) => book.item_id !== action.bookId);
- [ ] Kindly be noticed that you should create a new action type to get fetch the books ie: 
```
const FETCH_BOOK = 'bookStore/books/FETCH_BOOK';
```
![Screenshot from 2022-06-16 00-21-16](https://user-images.githubusercontent.com/33752735/173942198-a271c74a-acc1-4463-9a53-f7785ca4167b.png)

2022-06-16 09:04 UTC, Epaltechs commented
#### As required, in this commit I have created a new action type to fetch the books

2022-06-16 09:12 UTC, topeogunleye approved these changes
### Hi @Epaltechs, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 09:22 UTC, merged